### ISSUE TITLE
Create 2d, minimalist, rose logo.

### ISSUE THREAD

**Issue by DGKSK8LIFE** [Rose-OS/Desktop-Rose#1]

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/56693327/74086387-f9111080-4a47-11ea-804a-0b4b38cbd46d.png)
this but cropped, sound ok?

**Comment by DGKSK8LIFE** [comment]
no; has to be top-town, 2d with sharp stems

**Comment by DGKSK8LIFE** [comment]
pseudo minimalist kind of shit though: 
![RoseOS logo](https://user-images.githubusercontent.com/45473363/74088601-b823f680-4a5d-11ea-8bcb-5466420d1ae0.png)
